// apps/web/src/pages/EventDetail.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api, ApiError, type EventSummary, type Photo } from '../lib/api';
import { embedLargestFace, loadModels, NoFaceError, type LoadPhase } from '../lib/face';
import PhotoGrid from '../components/PhotoGrid.vue';
import type { GridItem } from '../lib/grid';
import PhotoGridSkeleton from '../components/PhotoGridSkeleton.vue';
import { plural } from '../lib/format';

const props = defineProps<{ slug: string }>();

const route = useRoute();
const router = useRouter();

type Tab = 'bib' | 'selfie' | 'upload';
const ALL_TABS: { id: Tab; label: string }[] = [
  { id: 'bib', label: 'Bib' },
  { id: 'selfie', label: 'Selfie' },
  { id: 'upload', label: 'Upload' },
];
const tab = ref<Tab>('bib');
const tabRefs = ref<HTMLButtonElement[]>([]);

const event = ref<EventSummary | null>(null);
const browse = ref<Photo[]>([]);
const cursor = ref<string | null>(null);
const loadingEvent = ref(true);
const loadingMore = ref(false);
const loadError = ref<string | null>(null);

const results = ref<GridItem[] | null>(null);
const searchedBy = ref<Tab | null>(null);
const searching = ref(false);
const searchError = ref<string | null>(null);
const searchNote = ref<string | null>(null);

const bib = ref('');

/**
 * Crop face results to the runner who actually matched.
 *
 * On by default because it is the point: these albums average about nine faces
 * per frame, so an uncropped result is a pack of runners and the person cannot
 * tell which one is them. The photographer's full frame is never more than a
 * tap away — the tile links to the untouched original either way — and the
 * toggle beside the count switches the whole grid back.
 */
const cropToFace = ref(true);
const faceSearched = computed(() => searchedBy.value === 'selfie' || searchedBy.value === 'upload');
// Set when an exact search found nothing but a looser one might. Widening is
// offered as a labelled choice, never done silently: a suffix match can return
// a different runner's photos and the runner has no way to tell.
const fuzzyOffered = ref(false);

const video = ref<HTMLVideoElement | null>(null);
const stream = ref<MediaStream | null>(null);
/** True once there is a picture to align to, which is what the panel switches on. */
const live = computed(() => !!stream.value);
const cameraError = ref<string | null>(null);

const modelPhase = ref<LoadPhase | null>(null);
const modelsReady = ref(false);
const showScore = import.meta.env.DEV;

const usesCamera = computed(() => tab.value !== 'bib');

// Events that hand out no bibs drop the tab entirely rather than showing a
// search that can only ever return nothing. Defaults to true so the tab does not
// flash away while the event is still loading.
const bibsEnabled = computed(() => event.value?.bibs_enabled !== false);
const TABS = computed(() => ALL_TABS.filter((t) => t.id !== 'bib' || bibsEnabled.value));

/**
 * The URL drives the bib search — on first paint, on Back/Forward, and on every
 * submit. Routing all of them through one watcher means a shared link and a
 * typed search take exactly the same path, so there is no second code path to
 * keep in step.
 */
watch(
  () => [route.query.bib, route.query.fuzzy] as const,
  ([rawBib, rawFuzzy]) => {
    const value = typeof rawBib === 'string' ? rawBib.trim() : '';
    if (!value) {
      // Only the bib search is URL-backed. A face search puts nothing in the
      // query, so clearing here on an empty param would wipe its results the
      // moment it finished.
      if (searchedBy.value === 'bib') clearResults();
      return;
    }
    bib.value = value;
    tab.value = 'bib';
    void searchBib(value, rawFuzzy === '1');
  },
  { immediate: true },
);

onMounted(async () => {
  try {
    const r = await api.getEvent(props.slug);
    event.value = r.event;
    // 'bib' is the initial tab because it is the right default for a race. If
    // this event has no bibs, move off it before anything renders a dead search.
    if (r.event.bibs_enabled === false && tab.value === 'bib') tab.value = 'selfie';
    browse.value = r.photos;
    cursor.value = r.cursor;
  } catch (e: any) {
    loadError.value = e.message;
  } finally {
    loadingEvent.value = false;
  }
});

onBeforeUnmount(stopCamera);

async function loadMore() {
  if (!cursor.value || loadingMore.value) return;
  loadingMore.value = true;
  try {
    const r = await api.getPhotos(props.slug, cursor.value);
    browse.value.push(...r.photos);
    cursor.value = r.cursor;
  } finally {
    loadingMore.value = false;
  }
}

/** Drop the current results without touching the URL. */
function clearResults() {
  fuzzyOffered.value = false;
  results.value = null;
  searchedBy.value = null;
  searchError.value = null;
  searchNote.value = null;
}

/**
 * Clear the results AND the query that produced them.
 *
 * The bib search lives in the URL (see the watcher below), so forgetting to
 * clear it here would leave the address bar claiming a search that is no
 * longer on screen — and a refresh would bring it straight back.
 */
function resetSearch() {
  clearResults();
  if (route.query.bib != null || route.query.fuzzy != null) {
    const query = { ...route.query };
    delete query.bib;
    delete query.fuzzy;
    router.replace({ query });
  }
}

function selectTab(t: Tab) {
  tab.value = t;
  resetSearch();
  if (t !== 'selfie') stopCamera();
  // Start the 16 MB model download the moment the user shows intent, so it
  // overlaps with them framing a selfie or picking a file.
  if (t !== 'bib' && !modelsReady.value) {
    loadModels((p) => {
      modelPhase.value = p;
      if (p === 'ready') modelsReady.value = true;
    }).catch(() => {});
  }
}

/** Roving arrow-key navigation, which the tab role contract requires. */
function onTabKey(e: KeyboardEvent, i: number) {
  const delta = e.key === 'ArrowRight' ? 1 : e.key === 'ArrowLeft' ? -1 : 0;
  if (!delta) return;
  e.preventDefault();
  const next = (i + delta + TABS.value.length) % TABS.value.length;
  selectTab(TABS.value[next].id);
  tabRefs.value[next]?.focus();
}

/**
 * Put the search in the URL and let the watcher run it.
 *
 * The URL is the single source of truth for bib search, which is what makes a
 * result bookmarkable, shareable, and able to survive a refresh — a runner who
 * finds their photos can send that link to whoever they ran with. It also means
 * Back steps out of a search rather than off the page.
 */
function submitBib(fuzzy = false) {
  const value = bib.value.trim();
  if (!value) return;
  const query: Record<string, string> = { ...(route.query as Record<string, string>), bib: value };
  if (fuzzy) query.fuzzy = '1'; else delete query.fuzzy;
  router.push({ query });
}

async function searchBib(value: string, fuzzy: boolean) {
  clearResults();
  searching.value = true;
  try {
    const r = await api.searchBib(props.slug, value, fuzzy);
    results.value = r.photos.map((photo) => ({ photo }));
    searchedBy.value = 'bib';
    fuzzyOffered.value = r.fuzzy_available;
    if (r.matched === 'suffix') {
      searchNote.value =
        `No photo of bib ${value} was found. These bibs merely END in ${value}, so they may be ` +
        `other runners — check the photo before assuming it is you.`;
    }
  } catch (e: any) {
    searchError.value = e.message;
  } finally {
    searching.value = false;
  }
}

async function runFaceSearch(source: Blob | HTMLVideoElement, via: Tab) {
  resetSearch();
  searching.value = true;
  try {
    await loadModels((p) => {
      modelPhase.value = p;
      if (p === 'ready') modelsReady.value = true;
    });
    const { vec, faceCount } = await embedLargestFace(source);
    const r = await api.searchFace(props.slug, vec);
    // bbox rides along so the grid can crop the tile to the face that matched.
    results.value = r.matches.map((m) => ({ photo: m.photo, score: m.score, bbox: m.bbox }));
    cropToFace.value = true;
    searchedBy.value = via;
    if (faceCount > 1 && r.matches.length) {
      searchNote.value = `Matched the largest of ${faceCount} faces in your photo.`;
    }
  } catch (e: any) {
    searchError.value =
      e instanceof NoFaceError
        ? 'We could not find a face in that image. Try a closer, front-facing photo in good light.'
        : e instanceof ApiError
          ? e.message
          : 'The search could not run on this device. Try the bib number instead.';
  } finally {
    searching.value = false;
  }
}

async function startCamera() {
  cameraError.value = null;
  try {
    stream.value = await navigator.mediaDevices.getUserMedia({
      video: { facingMode: 'user', width: { ideal: 1280 }, height: { ideal: 960 } },
      audio: false,
    });
    if (video.value) {
      video.value.srcObject = stream.value;
      await video.value.play();
    }
  } catch {
    cameraError.value = 'We could not open your camera. Check the permission in your browser, or use Upload instead.';
  }
}

function stopCamera() {
  stream.value?.getTracks().forEach((t) => t.stop());
  stream.value = null;
}

async function capture() {
  if (video.value && stream.value) await runFaceSearch(video.value, 'selfie');
}

async function onFile(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  if (file) await runFaceSearch(file, 'upload');
  // Reset so picking the same file twice fires change again.
  input.value = '';
}
</script>

<template>
  <template v-if="loadingEvent">
    <div class="skeleton" style="height: 30px; width: 60%; max-width: 380px" />
    <div class="skeleton skeleton-line short" style="margin-bottom: 28px" />
    <PhotoGridSkeleton />
  </template>

  <p v-else-if="loadError" class="notice err">{{ loadError }}</p>

  <template v-else-if="event">
    <h1>{{ event.name }}</h1>
    <p class="muted" style="margin: 0 0 var(--s-5)">
      {{ plural(event.photo_count, 'photo') }}
      <template v-if="event.status === 'partial'">
        · <span>some photos are still missing from the photographer</span>
      </template>
    </p>

    <div class="finder">
      <div class="segmented" role="tablist" aria-label="How to find your photos">
      <button
        v-for="(t, i) in TABS"
        :key="t.id"
        ref="tabRefs"
        role="tab"
        :id="`tab-${t.id}`"
        :aria-selected="tab === t.id"
        :aria-controls="`panel-${t.id}`"
        :tabindex="tab === t.id ? 0 : -1"
        @click="selectTab(t.id)"
        @keydown="onTabKey($event, i)">
        {{ t.label }}
      </button>
    </div>

    <div
      class="card"
      role="tabpanel"
      :id="`panel-${tab}`"
      :aria-labelledby="`tab-${tab}`"
      tabindex="-1">
      <template v-if="tab === 'bib'">
        <h3 class="ask-title">What number did you wear?</h3>
        <p class="ask-why">The number printed on your race bib. Usually 3–5 digits.</p>
        <form class="bib-form" @submit.prevent="submitBib()">
          <label class="sr-only" for="bib-input">Race bib number</label>
          <input
            id="bib-input" class="bib-entry" v-model="bib" inputmode="numeric" pattern="[0-9]*"
            autocomplete="off" enterkeyhint="search" placeholder="1274" />
          <button
            class="primary" type="submit" style="width: 100%; margin-top: var(--s-4)"
            :disabled="searching || !bib.trim()">
            Find my photos
          </button>
        </form>
      </template>

      <template v-else-if="tab === 'selfie'">
        <!-- The reason and the promise sit ABOVE the control that acts on
             them. "Never uploaded" is what decides whether a stranger will
             point a camera at their own face, so it cannot be a footnote read
             only by people who already said yes. -->
        <h3 class="ask-title">{{ live ? 'Fill the oval' : 'Let’s find you' }}</h3>
        <!-- Once the camera is live the guidance moves into the frame itself,
             where the person is already looking. Repeating it above as well
             costs ~36px, which on a 667px handset is the difference between
             the shutter button being reachable and being below the fold. -->
        <p v-if="!live" class="ask-why">
          Matched <strong>on this phone</strong> — never uploaded, never stored.
        </p>

        <div class="lens" :data-live="live">
          <video ref="video" playsinline muted aria-label="Camera preview" />
          <!-- Before permission there is no video, so the frame previews what
               will fill it rather than sitting empty. -->
          <div v-if="!live" class="ghost" aria-hidden="true" />
          <div v-else class="oval" aria-hidden="true" />
          <span v-if="live" class="hint">Good light, no sunglasses</span>
        </div>

        <button
          v-if="!live" class="primary" style="width: 100%; margin-top: var(--s-4)"
          @click="startCamera">
          Turn on camera
        </button>
        <button
          v-else class="primary" style="width: 100%; margin-top: var(--s-4)"
          :disabled="searching" @click="capture">
          Find my photos
        </button>

        <!-- The other routes are offered here, so nobody has to discover a tab
             to escape a camera they do not want to grant. -->
        <div class="alt-row">
          <button v-if="live" @click="stopCamera">Turn off camera</button>
          <button v-else @click="selectTab('upload')">Upload a photo</button>
          <button v-if="bibsEnabled" @click="selectTab('bib')">Use bib number</button>
        </div>

        <p v-if="cameraError" class="notice warn" style="margin-top: var(--s-3)">{{ cameraError }}</p>
      </template>

      <template v-else>
        <h3 class="ask-title">Pick a photo of yourself</h3>
        <p class="ask-why">
          Face large in the frame, looking at the camera. Matched <strong>on this phone</strong> —
          never uploaded, never stored.
        </p>
        <label class="sr-only" for="photo-upload">Photo of yourself</label>
        <input id="photo-upload" type="file" accept="image/*" :disabled="searching" @change="onFile" />
        <div class="alt-row">
          <button @click="selectTab('selfie')">Use the camera</button>
          <button v-if="bibsEnabled" @click="selectTab('bib')">Use bib number</button>
        </div>
      </template>

      <p v-if="usesCamera && modelPhase && !modelsReady" class="muted small" style="margin-top: var(--s-3)">
        <span class="spinner" /> Getting the face model ready (one time, about 16 MB)…
      </p>
      </div>
    </div>

    <p v-if="searchError" class="notice err" style="margin-top: var(--s-5)">{{ searchError }}</p>

    <!-- results ------------------------------------------------------- -->
    <template v-if="searching">
      <h2 style="margin-top: var(--s-6)"><span class="spinner" /> Searching {{ plural(event.photo_count, 'photo') }}…</h2>
      <PhotoGridSkeleton :count="8" />
    </template>

    <template v-else-if="results">
      <!-- The count header would only ever read "0 photos found" above a card
           that already says so. Show it when there is something to count. -->
      <div
        v-if="results.length"
        style="display: flex; align-items: baseline; justify-content: space-between;
               gap: var(--s-4); margin-top: var(--s-6); flex-wrap: wrap">
        <h2 style="margin: 0">
          {{ plural(results.length, 'photo') }} found
        </h2>
        <div class="btn-row">
          <button v-if="faceSearched" @click="cropToFace = !cropToFace">
            {{ cropToFace ? 'Show full frames' : 'Crop to me' }}
          </button>
          <button @click="resetSearch">Show all photos</button>
        </div>
      </div>

      <p v-if="searchNote" class="notice" style="margin: var(--s-3) 0">{{ searchNote }}</p>

      <template v-if="results.length">
        <p class="muted small" style="margin: var(--s-3) 0 var(--s-4)">
          Tap a photo to open the full-size original from the photographer.
        </p>
        <PhotoGrid
          :items="results"
          :show-score="showScore"
          :crop="faceSearched && cropToFace"
          show-time
          animate />
      </template>

      <!-- An empty result is the moment the user is most likely to give up, so
           it teaches the next move rather than saying "nothing found". -->
      <div v-else class="card" style="margin-top: var(--s-6)">
        <h2>No matches yet</h2>
        <template v-if="searchedBy === 'bib'">
          <p class="muted" style="margin-top: 0">
            No photo of bib {{ bib }} has been indexed. Bib numbers get missed when they are
            folded, covered by a hand, or turned away from the camera.
          </p>
          <p class="muted small">Try finding yourself by face instead — it works even when your bib is hidden.</p>
          <div class="btn-row">
            <button class="primary" @click="selectTab('selfie')">Take a selfie</button>
            <button v-if="fuzzyOffered" @click="submitBib(true)">Try similar numbers</button>
            <button @click="selectTab('upload')">Upload a photo</button>
            <button @click="resetSearch">Show all photos</button>
          </div>
        </template>
        <template v-else>
          <p class="muted" style="margin-top: 0">
            Nobody matching that face turned up in this event's photos.
          </p>
          <ul class="muted small" style="padding-left: 1.1em; margin-bottom: var(--s-4)">
            <li>Use a photo where your face is large, lit from the front, and not in sunglasses.</li>
            <li>Race photos are often taken side-on — try a second, different photo.</li>
            <li v-if="bibsEnabled">If you know your bib number, that search is exact.</li>
          </ul>
          <div class="btn-row">
            <button v-if="bibsEnabled" class="primary" @click="selectTab('bib')">Search by bib number</button>
            <button @click="resetSearch">Show all photos</button>
          </div>
        </template>
      </div>
    </template>

    <!-- browse -------------------------------------------------------- -->
    <template v-else>
      <h2 style="margin-top: var(--s-6)">All photos</h2>
      <PhotoGrid :items="browse.map((photo) => ({ photo }))" />
      <p v-if="!browse.length" class="muted">This event has no photos yet.</p>
      <div v-if="cursor" style="margin-top: var(--s-5)">
        <button :disabled="loadingMore" @click="loadMore">
          <span v-if="loadingMore" class="spinner" /> {{ loadingMore ? 'Loading…' : 'Load more photos' }}
        </button>
      </div>
    </template>
  </template>
</template>

// apps/web/src/react/pages/EventDetail.tsx
/**
 * One album.
 *
 * The runner has one job here and about ten seconds of patience, so the page
 * opens on the thing that does the job: a bib, at the size they wore it. Face
 * search is the second route, offered plainly for the case the bib cannot answer
 * — folded, covered, turned away — which is roughly 4 photos in 10.
 *
 * The URL carries the search, so a result is bookmarkable and shareable, and Back
 * steps out of a search rather than off the page.
 */
import { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { ScanFace } from 'lucide-react';
import { api, type EventSummary, type FaceMatch, type Photo } from '@/lib/api';
import { plural } from '@/lib/format';
import { Bib } from '../components/Bib';
import { BibInput } from '../components/BibInput';
import { PhotoWall, type WallItem } from '../components/PhotoWall';
import { FaceSearch } from '../components/FaceSearch';
import { BackLink } from '../components/BackLink';
import { Button } from '@/components/ui/button';
import { AlbumSkeleton } from '../components/AlbumSkeleton';
import { useDeferredLoading } from '../useDeferredLoading';

export default function EventDetail() {
  const { slug = '' } = useParams();
  const [params, setParams] = useSearchParams();
  const searched = params.get('bib') ?? '';

  const [event, setEvent] = useState<EventSummary | null>(null);
  const [photos, setPhotos] = useState<Photo[]>([]);
  // Cursor pagination for the browse feed. The album is 1,070 photos at SheRuns
  // and 32,796 at Angkor, so it arrives a page at a time.
  const [cursor, setCursor] = useState<string | null>(null);
  const [loadingMore, setLoadingMore] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [draft, setDraft] = useState(searched);
  const [results, setResults] = useState<WallItem[] | null>(null);
  const [alternatives, setAlternatives] = useState<string[]>([]);
  const [searching, setSearching] = useState(false);

  // Face results live outside the URL, unlike a bib search: the query is a
  // selfie, so there is nothing shareable to put in a link and a reload could
  // not reproduce it. Clearing them is what returning to the album means.
  const [faceOpen, setFaceOpen] = useState(false);
  const [faceResults, setFaceResults] = useState<WallItem[] | null>(null);
  const [faceNote, setFaceNote] = useState<string | null>(null);

  const showSkeleton = useDeferredLoading(loading);

  useEffect(() => {
    let live = true;
    // Reset on a slug change. React Router keeps this component mounted when only
    // the parameter changes, so without this the previous album's photos stay on
    // screen under the new album's title until the request lands — which is worse
    // than a placeholder, because it looks like real content for the wrong race.
    setLoading(true);
    setPhotos([]);
    setCursor(null);
    setEvent(null);
    api.getEvent(slug)
      .then((r) => { if (!live) return; setEvent(r.event); setPhotos(r.photos); setCursor(r.cursor); })
      .catch((e: Error) => { if (live) setError(e.message); })
      .finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [slug]);

  // The URL is the source of truth: this runs for a typed search, for Back and
  // Forward, and for someone opening a shared link.
  useEffect(() => {
    // Clearing the search clears the bib with it. Handled here rather than in the
    // button, so Back out of a search and a shared link with no bib both leave an
    // empty bib too — a number still sitting in it after "Show the whole album"
    // reads as a filter that is still on.
    if (!searched) { setResults(null); setAlternatives([]); setDraft(''); return; }
    let live = true;
    setSearching(true);
    setDraft(searched);
    api.searchBib(slug, searched)
      .then((r) => {
        if (!live) return;
        setResults(r.photos.map((photo) => ({ photo })));
        setAlternatives(r.alternatives ?? []);
      })
      .catch((e: Error) => { if (live) setError(e.message); })
      .finally(() => { if (live) setSearching(false); });
    return () => { live = false; };
  }, [slug, searched]);

  // Guarded by the cursor itself rather than a ref: onLoadMore fires from an
  // observer that can trigger twice before state settles, and appending the same
  // page twice would duplicate keys.
  const loadMore = async () => {
    if (!cursor || loadingMore) return;
    setLoadingMore(true);
    try {
      const r = await api.getPhotos(slug, cursor);
      setPhotos((prev) => [...prev, ...r.photos]);
      setCursor(r.cursor);
    } catch (e) { setError((e as Error).message); }
    finally { setLoadingMore(false); }
  };

  const search = (v: string) => {
    const value = v.trim();
    setFaceResults(null);
    setFaceNote(null);
    // REPLACE, not push. A search refines the view you are already on; it is not
    // a new page. Pushing meant ten searches left ten history entries, so "All
    // events" — which goes back — stepped through all of them one at a time
    // instead of returning to the list. Replacing keeps the album as a single
    // entry, so one step back is the list, with its scroll position intact.
    // "Show the whole album" is how you undo a search.
    setParams(value ? { bib: value } : {}, { replace: true });
  };

  const onFaceResults = (matches: FaceMatch[], faceCount: number) => {
    setParams({}, { replace: true });
    // The score decides the ORDER and the cut-off, and that is where it belongs.
    // Printed on every tile it asked the runner to audit the matcher — a number
    // they cannot act on, over a photo they can see for themselves.
    setFaceResults(matches.map((m) => ({ photo: m.photo })));
    setFaceNote(faceCount > 1
      ? `Matched the largest of ${faceCount} faces in your photo.`
      : null);
  };

  // Nothing at all for a fast load — see useDeferredLoading. The album answers in
  // ~120ms on a warm connection, and a placeholder drawn for that long is a blink.
  if (showSkeleton) return <AlbumSkeleton />;
  if (loading) return <div className="min-h-screen" />;
  if (error) {
    return <p className="rounded-md border border-destructive/45 px-4 py-3 text-destructive">{error}</p>;
  }

  const bibsOn = event?.bibs_enabled !== false;

  return (
    <div className="pb-16">
      <BackLink to="/">All events</BackLink>

      <header className="mb-8">
        <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{event?.name}</h1>
        <p className="tabular mt-1 text-sm text-muted-foreground">
          {plural(event?.photo_count ?? 0, 'photo')}
          {event?.face_count ? ` · ${plural(event.face_count, 'face')} found` : ''}
        </p>
      </header>

      {/* Face search is ALWAYS offered. Only the bib is conditional — and an event
          with no bibs is precisely the one where a face is the only way in, so
          hiding both together (as this did) removed the search from the albums
          that depend on it most. */}
      {/* One reserved height for both variants. Whether this race used bibs is
          not known until the event loads, so a panel that sizes to its contents
          moves the whole wall down the page the moment the answer arrives. */}
      <div className="mb-10 flex min-h-[22.5rem] flex-col items-center justify-center gap-6
                      rounded-xl border border-border bg-card/40 px-4 py-10">
        {bibsOn && (
          <>
            <BibInput value={draft} onChange={setDraft} onSubmit={() => search(draft)} band={event?.name} />
            <div className="flex items-center gap-3 text-sm">
              <span className="text-muted-foreground">or</span>
              <Button variant="outline" size="lg" onClick={() => setFaceOpen(true)}>
                <ScanFace /> Find me by face
              </Button>
            </div>
          </>
        )}
        {!bibsOn && (
          <>
            <p className="max-w-sm text-center text-muted-foreground">
              This race had no bib numbers, so your face is the way in.
            </p>
            <Button size="lg" onClick={() => setFaceOpen(true)}>
              <ScanFace /> Find me by face
            </Button>
          </>
        )}
        <p className="max-w-sm text-center text-xs text-muted-foreground">
          Face matching runs on your phone. Your selfie is never uploaded.
        </p>
      </div>

      {faceResults ? (
        <section>
          <div className="mb-6">
            <p className="tabular font-[family-name:var(--font-display)] text-xl font-bold">
              {plural(faceResults.length, 'photo')} of you
            </p>
            {faceNote && <p className="text-sm text-muted-foreground">{faceNote}</p>}
            <button
              onClick={() => { setFaceResults(null); setFaceNote(null); }}
              className="text-sm text-muted-foreground underline-offset-4 hover:underline"
            >
              Show the whole album
            </button>
          </div>
          {faceResults.length === 0 ? (
            <div className="rounded-xl border border-border p-8 text-center">
              <p className="mb-1 font-[family-name:var(--font-display)] text-lg font-bold">
                Nobody matching that face
              </p>
              <p className="mx-auto max-w-md text-sm text-muted-foreground">
                Race photos are often taken side-on. Try a second picture, or search
                by your number.
              </p>
            </div>
          ) : (
            <PhotoWall items={faceResults} />
          )}
        </section>
      ) : searched ? (
        <section>
          <div className="mb-6 flex flex-wrap items-center gap-4">
            <Bib value={searched} size="sm" band={event?.name} />
            <div>
              <p className="tabular font-[family-name:var(--font-display)] text-xl font-bold">
                {searching ? 'Looking…' : plural(results?.length ?? 0, 'photo')}
              </p>
              <button onClick={() => search('')} className="text-sm text-muted-foreground underline-offset-4 hover:underline">
                Show the whole album
              </button>
            </div>
          </div>

          {alternatives.length > 0 && (
            <p className="mb-6 text-sm text-muted-foreground">
              This race numbers by category. The same number also exists as{' '}
              {alternatives.map((alt, i) => (
                <span key={alt}>
                  <button onClick={() => search(alt)} className="text-primary underline underline-offset-4">{alt}</button>
                  {i < alternatives.length - 1 ? ', ' : ''}
                </span>
              ))}.
            </p>
          )}

          {!searching && results?.length === 0 ? (
            <div className="rounded-xl border border-border p-8 text-center">
              <p className="mb-1 font-[family-name:var(--font-display)] text-lg font-bold">
                No photo of that number yet
              </p>
              <p className="mx-auto mb-5 max-w-md text-sm text-muted-foreground">
                Numbers get folded, covered by a hand, or turned away from the camera.
                Your face does not.
              </p>
              <Button size="lg" onClick={() => setFaceOpen(true)}><ScanFace /> Find me by face</Button>
            </div>
          ) : (
            <PhotoWall items={results ?? []} />
          )}
        </section>
      ) : (
        <PhotoWall
          items={photos.map((photo) => ({ photo }))}
          onLoadMore={loadMore}
          hasMore={!!cursor}
          loadingMore={loadingMore}
        />
      )}

      <FaceSearch
        slug={slug}
        open={faceOpen}
        onClose={() => setFaceOpen(false)}
        onResults={onFaceResults}
      />
    </div>
  );
}
