// apps/web/src/pages/EventList.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RouterLink } from 'vue-router';
import { api, type EventSummary } from '../lib/api';
import { formatDate, plural } from '../lib/format';
import { eventListCache } from '../lib/cache';

// Read during setup, so coming back from an album re-renders the same list
// instead of replacing it with skeleton cards for a second. See lib/cache.ts.
const restored = eventListCache.read('events');

const events = ref<EventSummary[]>(restored ?? []);
const loading = ref(!restored);
const error = ref<string | null>(null);

onMounted(async () => {
  if (restored) return;
  try {
    events.value = (await api.listEvents()).events;
    eventListCache.write('events', events.value);
  } catch (e: any) {
    error.value = e.message;
  } finally {
    loading.value = false;
  }
});
</script>

<template>
  <!--
    The front door.

    This page gets more traffic than any other and used to do the least work: a
    list of cards and one sentence. The three facts below are the ones that
    decide whether a stranger will try the search at all — that it is free, that
    their face never leaves their phone, and that it still works when their bib
    doesn't. None of them were stated anywhere.
  -->
  <header class="masthead">
    <h1>Find yourself in the race photos.</h1>
    <p class="lede">
      Pick your event, then search by the number you wore or by your own face.
      It takes about ten seconds.
    </p>
  </header>

  <div class="assurances">
    <div>
      <h3>Free, and no account</h3>
      <p>Every photo opens full-size from the photographer's own album. There is nothing to sign up for.</p>
    </div>
    <div>
      <h3>Your face stays on your phone</h3>
      <p>The matching runs in your browser. Your selfie is never uploaded and never stored.</p>
    </div>
    <div>
      <h3>Works when your bib doesn't</h3>
      <p>Numbers get folded, covered, or turned away from the camera. Face search doesn't mind.</p>
    </div>
  </div>

  <div class="section-head">
    <h2>Events</h2>
    <span v-if="!loading && events.length" class="muted small">
      {{ plural(events.length, 'album') }} published
    </span>
  </div>

  <!-- Skeleton cards hold the grid's real shape so nothing reflows on arrival. -->
  <div v-if="loading" class="event-grid" aria-hidden="true">
    <div v-for="i in 3" :key="i" class="event-card">
      <div class="skeleton" style="aspect-ratio: 16 / 9; border-radius: 0" />
      <div class="body">
        <div class="skeleton skeleton-line" style="width: 70%" />
        <div class="skeleton skeleton-line short" />
      </div>
    </div>
  </div>
  <p v-if="loading" class="sr-only" role="status">Loading events</p>

  <p v-else-if="error" class="notice err">{{ error }}</p>

  <div v-else-if="!events.length" class="card">
    <h2>No events published yet</h2>
    <p class="muted" style="margin-top: 0">
      Photos appear here once an organizer has uploaded and indexed an album — usually a few
      days after race day.
    </p>
    <p class="muted small" style="margin-bottom: 0">
      Organizing a race? <RouterLink to="/admin" style="text-decoration: underline">Publish your album</RouterLink>.
    </p>
  </div>

  <div v-else class="event-grid stagger">
    <RouterLink
      v-for="(e, i) in events" :key="e.id"
      :to="`/e/${e.slug}`" class="event-card" :style="{ '--i': i }">
      <div class="banner">
        <!-- The blurred backdrop is the same picture, so it is decorative:
             announcing it twice would only be noise to a screen reader. -->
        <template v-if="e.banner_url">
          <img class="banner-fill" :src="e.banner_url" alt="" aria-hidden="true" loading="lazy" />
          <img class="banner-img" :src="e.banner_url" alt="" loading="lazy" />
        </template>
      </div>
      <div class="body">
        <div class="name">{{ e.name }}</div>
        <div class="muted small">
          <span v-if="e.event_date">{{ formatDate(e.event_date) }} · </span>
          {{ plural(e.photo_count, 'photo') }}
          · {{ e.bibs_enabled ? 'Bib or face' : 'Face search' }}
          <span v-if="e.status === 'partial'"> · still growing</span>
        </div>
      </div>
    </RouterLink>
  </div>
</template>

// apps/web/src/react/pages/EventList.tsx
/**
 * The front door.
 *
 * This page gets more traffic than any other and used to do the least work: a
 * list of cards and one sentence. The three assurances below are the ones that
 * decide whether a stranger will try the search at all — that it is free, that
 * their face never leaves their phone, and that it still works when their bib
 * doesn't.
 */
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, type EventSummary } from '@/lib/api';
import { eventListCache } from '@/lib/cache';
import { formatDate, plural } from '@/lib/format';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Banner } from '../components/Banner';

const ASSURANCES = [
  ['Free, and no account',
   "Every photo opens full-size from the photographer's own album. There is nothing to sign up for."],
  ['Your face stays on your phone',
   'The matching runs in your browser. Your selfie is never uploaded and never stored.'],
  ["Works when your bib doesn't",
   "Numbers get folded, covered, or turned away from the camera. Face search doesn't mind."],
] as const;

export default function EventList() {
  // Read during the first render, so coming back from an album re-renders the
  // same list instead of replacing it with skeleton cards for a second.
  const restored = eventListCache.read('events');
  const [events, setEvents] = useState<EventSummary[]>(restored ?? []);
  const [loading, setLoading] = useState(!restored);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (restored) return;
    let live = true;
    api.listEvents()
      .then((r) => { if (!live) return; setEvents(r.events); eventListCache.write('events', r.events); })
      .catch((e: Error) => { if (live) setError(e.message); })
      .finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <header className="mb-7">
        <h1 className="mb-1 text-3xl font-bold tracking-tight text-balance">
          Find yourself in the race photos.
        </h1>
        <p className="max-w-[60ch] text-muted-foreground">
          Pick your event, then search by the number you wore or by your own face.
          It takes about ten seconds.
        </p>
      </header>

      <div className="mb-7 grid gap-4 sm:grid-cols-3">
        {ASSURANCES.map(([title, body]) => (
          <div key={title}>
            <h3 className="mb-1 font-semibold">{title}</h3>
            <p className="text-sm text-muted-foreground">{body}</p>
          </div>
        ))}
      </div>

      <div className="mb-3 flex items-center justify-between">
        <h2 className="font-semibold">Events</h2>
        {!loading && events.length > 0 && (
          <span className="text-sm text-muted-foreground">
            {plural(events.length, 'album')} published
          </span>
        )}
      </div>

      {/* Skeletons hold the grid's real shape so nothing reflows on arrival. */}
      {loading ? (
        <>
          <div aria-hidden className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {[0, 1, 2].map((i) => (
              <Card key={i} className="overflow-hidden p-0">
                <Skeleton className="aspect-video w-full rounded-none" />
                <div className="space-y-2 p-4">
                  <Skeleton className="h-4 w-[70%]" />
                  <Skeleton className="h-3 w-[40%]" />
                </div>
              </Card>
            ))}
          </div>
          <p role="status" className="sr-only">Loading events</p>
        </>
      ) : error ? (
        <p className="rounded-md border border-destructive/45 bg-card px-4 py-3 text-sm text-destructive">
          {error}
        </p>
      ) : !events.length ? (
        <Card className="p-5">
          <h2 className="font-semibold">No events published yet</h2>
          <p className="text-muted-foreground">
            Photos appear here once an organizer has uploaded and indexed an album —
            usually a few days after race day.
          </p>
          <p className="text-sm text-muted-foreground">
            Organizing a race? <Link to="/admin" className="underline">Publish your album</Link>.
          </p>
        </Card>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {events.map((e) => (
            <Link key={e.id} to={`/e/${e.slug}`}>
              <Card className="overflow-hidden p-0 transition-colors hover:border-ring">
                <Banner url={e.banner_url} />
                <div className="p-4">
                  <div className="mb-0.5 font-semibold">{e.name}</div>
                  <div className="text-sm text-muted-foreground">
                    {e.event_date && <>{formatDate(e.event_date)} · </>}
                    {plural(e.photo_count, 'photo')}
                    {' · '}{e.bibs_enabled ? 'Bib or face' : 'Face search'}
                    {e.status === 'partial' && <> · still growing</>}
                  </div>
                </div>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </>
  );
}
