// apps/web/src/react/pages/AdminPhotos.tsx
/**
 * Inspect photos — what the detector and the OCR actually saw.
 *
 * The only screen that shows the pipeline's own view: a box per face, labelled
 * with the bib read from that runner's torso. It exists to answer one question
 * an aggregate never can — "why is this photo missing from her results?" — and
 * to let an operator fix it by hand.
 *
 * The filters are the three states worth acting on, not a taxonomy. "No bib" is
 * where corrections happen; "no face" is usually the photographer's framing, not
 * a fault.
 */
import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { api } from '@/lib/api';
import { plural } from '@/lib/format';
import { BackLink } from '../components/BackLink';
import { Button } from '@/components/ui/button';

type Filter = 'all' | 'no-face' | 'no-bib';
type Row = Awaited<ReturnType<typeof api.admin.photos>>['photos'][number];

const FILTERS: [Filter, string][] = [['all', 'All'], ['no-face', 'No face'], ['no-bib', 'No bib']];

export default function AdminPhotos() {
  const { id = '' } = useParams();
  const [filter, setFilter] = useState<Filter>('all');
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState('');
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const r = await api.admin.photos(id, null, filter);
      setRows(r.photos);
      setError(null);
    } catch (e) { setError((e as Error).message); }
    finally { setLoading(false); }
  }, [id, filter]);

  useEffect(() => { load(); }, [load]);

  async function saveBib(faceId: string) {
    const value = draft.trim();
    setEditing(null);
    try { await api.admin.setFaceBib(faceId, value); await load(); }
    catch (e) { setError((e as Error).message); }
  }

  return (
    <div className="pb-16">
      <BackLink to={`/admin/e/${id}`}>Back to the album</BackLink>

      <header className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight">Inspect photos</h1>
        <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
          Each box is a detected face, labelled with the bib read from that
          runner's torso. <span className="tabular text-foreground">?</span> means a
          face was found but no number could be read — click any label to type it in.
        </p>
      </header>

      <div className="mb-6 inline-flex rounded-lg border border-border p-1">
        {FILTERS.map(([f, label]) => (
          <button key={f} onClick={() => setFilter(f)} aria-pressed={filter === f}
                  className={`rounded-md px-4 py-1.5 text-sm ${filter === f ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>
            {label}
          </button>
        ))}
      </div>

      {error && <p className="mb-6 rounded-md border border-destructive/45 px-4 py-3 text-sm text-destructive">{error}</p>}

      {loading ? (
        <p className="flex items-center gap-2 py-10 text-muted-foreground"><Loader2 className="size-4 animate-spin" /> Loading</p>
      ) : !rows.length ? (
        <p className="rounded-xl border border-border p-8 text-center text-sm text-muted-foreground">
          Nothing here — which for this filter is good news.
        </p>
      ) : (
        <>
          <p className="tabular mb-4 text-sm text-muted-foreground">{plural(rows.length, 'photo')}</p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {rows.map((p) => (
              <figure key={p.id} className="overflow-hidden rounded-lg border border-border">
                <div className="relative bg-muted">
                  {p.thumb_url && <img src={p.thumb_url} alt="" loading="lazy" className="block w-full" />}
                  {p.faces.map((f) => (
                    <div
                      key={f.id}
                      className="absolute border-2 border-primary"
                      style={{ left: `${f.x * 100}%`, top: `${f.y * 100}%`, width: `${f.w * 100}%`, height: `${f.h * 100}%` }}
                    >
                      {editing === f.id ? (
                        <input
                          autoFocus
                          value={draft}
                          onChange={(e) => setDraft(e.target.value)}
                          onBlur={() => setEditing(null)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') saveBib(f.id);
                            if (e.key === 'Escape') setEditing(null);
                          }}
                          className="tabular absolute -bottom-7 left-0 w-20 rounded bg-background px-1 py-0.5
                                     text-xs text-foreground outline-none ring-2 ring-primary"
                        />
                      ) : (
                        <button
                          onClick={() => { setEditing(f.id); setDraft(f.bib ?? ''); }}
                          className="tabular absolute -bottom-6 left-0 rounded bg-primary px-1.5 py-0.5
                                     text-xs font-bold text-primary-foreground"
                        >
                          {f.bib ?? '?'}
                        </button>
                      )}
                    </div>
                  ))}
                </div>
                <figcaption className="flex items-center justify-between px-3 py-2 text-xs text-muted-foreground">
                  <span>{p.faces.length ? plural(p.faces.length, 'face') : 'no face found'}</span>
                  <a href={p.original_url} target="_blank" rel="noreferrer" className="underline-offset-4 hover:underline">
                    original
                  </a>
                </figcaption>
              </figure>
            ))}
          </div>
        </>
      )}

      <Button variant="outline" className="mt-8" render={<Link to={`/admin/e/${id}`} />}>
        Back to the album
      </Button>
    </div>
  );
}

// apps/web/src/pages/AdminPhotos.vue
<script setup lang="ts">
/**
 * Visual debugger: every photo with its detected faces boxed and its read bib
 * printed on the box.
 *
 * Counts tell you 46 photos have no bib; they cannot tell you WHY. Seeing the
 * frame with nothing boxed, or a box over a runner whose number was misread, is
 * the difference between guessing at thresholds and knowing which stage failed.
 */
import { computed, onMounted, ref, watch } from 'vue';
import { RouterLink } from 'vue-router';
import { api } from '../lib/api';

const props = defineProps<{ id: string }>();
type Row = Awaited<ReturnType<typeof api.admin.photos>>['photos'][number];

const FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'no_face', label: 'No face' },
  { id: 'no_bib', label: 'No bib' },
  { id: 'has_bib', label: 'Has bib' },
] as const;

const filter = ref<(typeof FILTERS)[number]['id']>('all');
const photos = ref<Row[]>([]);
const cursor = ref<string | null>(null);
const loading = ref(true);
const loadingMore = ref(false);
const error = ref<string | null>(null);
const zoom = ref<Row | null>(null);

async function load(reset = false) {
  if (reset) { photos.value = []; cursor.value = null; loading.value = true; }
  else loadingMore.value = true;
  try {
    const r = await api.admin.photos(props.id, reset ? null : cursor.value, filter.value);
    photos.value = reset ? r.photos : [...photos.value, ...r.photos];
    cursor.value = r.cursor;
    error.value = null;
  } catch (e: any) { error.value = e.message; }
  finally { loading.value = false; loadingMore.value = false; }
}

onMounted(() => load(true));
watch(filter, () => load(true));

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;
const summary = computed(() => {
  const p = photos.value;
  return {
    shown: p.length,
    noFace: p.filter((x) => !x.faces.length).length,
    noBib: p.filter((x) => !x.bibs.length).length,
  };
});
</script>

<template>
  <p style="margin: 0 0 var(--s-4)">
    <RouterLink :to="`/admin/e/${id}`" class="muted small">← Event</RouterLink>
  </p>
  <h1>Inspect photos</h1>
  <p class="lede">
    Green boxes are detected faces. The label on a box is the bib read from that
    runner's torso; <strong>?</strong> means a face was found but no number could be read.
  </p>

  <div class="segmented" role="tablist" aria-label="Filter photos">
    <button v-for="f in FILTERS" :key="f.id" role="tab"
            :aria-selected="filter === f.id" @click="filter = f.id">{{ f.label }}</button>
  </div>

  <p v-if="error" class="notice err">{{ error }}</p>
  <p v-if="loading" class="muted"><span class="spinner" /> Loading…</p>

  <template v-else>
    <p class="muted small">
      Showing {{ summary.shown }} · {{ summary.noFace }} with no face · {{ summary.noBib }} with no bib
    </p>

    <div class="photo-grid" style="grid-template-columns: repeat(auto-fill, minmax(260px, 1fr))">
      <figure v-for="p in photos" :key="p.id">
        <button class="inspect-tile" @click="zoom = p">
          <img :src="p.thumb_url ?? ''" alt="" loading="lazy" decoding="async" />
          <span v-for="(f, i) in p.faces" :key="i" class="face-box"
                :style="{ left: pct(f.x), top: pct(f.y), width: pct(f.w), height: pct(f.h) }">
            <span class="face-tag">{{ f.bib || '?' }}</span>
          </span>
          <span v-if="!p.faces.length" class="no-face-flag">no face detected</span>
        </button>
        <figcaption class="muted small" style="margin-top: 4px">
          <span v-if="p.bibs.length">
            bibs: {{ p.bibs.map((b) => b.bib).join(', ') }}
          </span>
          <span v-else>no bib read</span>
          ·
          <a :href="p.original_url" target="_blank" rel="noopener" class="mono-id">original</a>
        </figcaption>
      </figure>
    </div>

    <p v-if="!photos.length" class="muted">No photos match this filter.</p>
    <div v-if="cursor" style="margin-top: var(--s-5)">
      <button :disabled="loadingMore" @click="load(false)">
        <span v-if="loadingMore" class="spinner" /> Load more
      </button>
    </div>
  </template>

  <!-- zoom -->
  <div v-if="zoom" class="zoom-backdrop" @click="zoom = null">
    <div class="zoom-inner" @click.stop>
      <div class="inspect-tile" style="max-height: 76vh">
        <img :src="zoom.thumb_url ?? ''" alt="" />
        <span v-for="(f, i) in zoom.faces" :key="i" class="face-box"
              :style="{ left: pct(f.x), top: pct(f.y), width: pct(f.w), height: pct(f.h) }">
          <span class="face-tag">{{ f.bib || '?' }}</span>
        </span>
      </div>
      <div class="row" style="border-bottom: 0">
        <div class="row-main small">
          <strong>{{ zoom.faces.length }}</strong> faces ·
          bibs: {{ zoom.bibs.length ? zoom.bibs.map((b) => `${b.bib} (${(b.conf ?? 0).toFixed(2)})`).join(', ') : 'none' }}
        </div>
        <div class="row-actions">
          <a class="btn file-btn" :href="zoom.original_url" target="_blank" rel="noopener">Open original</a>
          <button @click="zoom = null">Close</button>
        </div>
      </div>
    </div>
  </div>
</template>
